# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c2a637612539eb2484e0c38b82e6797"
name = "dev-store-app"
application_url = "https://departmental-colony-ata-showed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://departmental-colony-ata-showed.trycloudflare.com/api/auth" ]
